### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by QueenEvanescence** [Arthur-Milchior/anki-enhance-main-window#111]
Got this message when i tried to open review heatmap card browser

Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-11 23:24:13

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "C:\Users\Nancy\AppData\Roaming\Anki2\addons21\877182321\column.py", line 12, in _linkHandler
    (cmd, arg) = url.split(":")
ValueError: too many values to unpack (expected 2)

Saw that on the main Addon page someone had already written the corrected _linkHandlercode as follows:
def _linkHandler(self, url):
    if ":" in url:
        (cmd, arg) = url.split(":")
        param = url.split(":")
        cmd = param[0]
        arg = param[1:len(param)-1]
        if cmd == "dragColumn":
            return columnHandler(self, arg)
        elif cmd == "optsColumn":
            return columnOptions(self, arg)
    return lastHandler(self, url)
    
    
  so i copy pasted it but the problem persists
    
    
    the card browser opens perfectly when i disable the enhance main window addon
    could you please help me out? Thank you in advance!!

**Comment by QueenEvanescence** [comment]
sorry i realized that i had missed adding  ## to the corrected code
