### ISSUE TITLE
'AddonManager' object has no attribute 'setConfigUpdatedAction'

### ISSUE THREAD

**Issue by oladhari** [Arthur-Milchior/anki-enhance-main-window#54]
System: Ubuntu
```console
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Anki 2.1.0+dfsg~b36-1  installed via the Ubuntu softwares application.
More Overview stats Anki addon installed via its Anki 2.1 code in https://ankiweb.net/shared/info/2116130837

When restarting Anki, I get the following error:

```console
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Enhance main window':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 57, in loadAddons
    __import__(dir)
  File "/home/oladhari/.local/share/Anki2/addons21/877182321/__init__.py", line 1, in <module>
    from . import changeFunction
  File "/home/oladhari/.local/share/Anki2/addons21/877182321/changeFunction.py", line 1, in <module>
    from .node import idToNode, renderDeckTree
  File "/home/oladhari/.local/share/Anki2/addons21/877182321/node.py", line 8, in <module>
    from .config import getUserOption, writeConfig, getFromName
  File "/home/oladhari/.local/share/Anki2/addons21/877182321/config.py", line 30, in <module>
    mw.addonManager.setConfigUpdatedAction(__name__,update)
AttributeError: 'AddonManager' object has no attribute 'setConfigUpdatedAction'
```

I couldn't figure out why the addonManager (from mw from aqt) doesn't have the setConfigUpdatedAction, and how to update the aqt package.

Can you help me figuring this out?
Please let me know if you need more information.

**Comment by Arthur-Milchior** [comment]
Ubuntu's package is not up to date at all. If you want to use this add on
you should go to anki's website and download a more recent version

Le mer. 15 mai 2019 à 08:34, Ladhari Oussama <notifications@github.com> a
écrit :

**Comment by oladhari** [comment]
@Arthur-Milchior 
Thank you for your reply! I missed your reply

**Comment by oladhari** [comment]
the problem was resolved, thank you for your help, closing the issue
